name: Publish package to PyPI

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    uses: ./.github/workflows/build_package.yml

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Flatten dist directory
        run: |
          mkdir -p flat_dist
          find dist -name '*.whl' -exec cp {} flat_dist/ \;

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          packages-dir: flat_dist
